name: CI Configurable

on:
  workflow_call:
    outputs:
      technology:
        description: "The technology used in the project"
        value: ${{ jobs.detect-and-pass.outputs.technology }}
      project-name:
        description: "The name of the project"
        value: ${{ jobs.detect-and-pass.outputs.project-name }}
    # secrets:
    #   SONAR_TOKEN:
    #     required: false
    #   ARTIFACTORY_TOKEN:
    #     required: false

jobs:
  detect-and-pass:
    runs-on: ubuntu-latest
    outputs:
      technology: ${{ steps.config.outputs.technology }}
      project-name: ${{ steps.config.outputs.project-name }}
    steps:
      - uses: actions/checkout@v6
      - id: config
        run: |
          # Parse .github/pipeline-config.yml
          TECH=$(yq '.technology' .github/pipeline-config.yml)
          PROJECT=$(yq '.project-name' .github/pipeline-config.yml)
          echo "$TECH"
          echo "$PROJECT"
          echo "technology=$TECH" >> $GITHUB_OUTPUT
          echo "project-name=$PROJECT" >> $GITHUB_OUTPUT
